-- Northstar's PostgreSQL system of record.
-- This migration is intentionally additive and is applied by
-- scripts/postgres/migrate.mjs under an advisory lock.

CREATE TABLE northstar_meta (
  key text PRIMARY KEY,
  value jsonb NOT NULL,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE users (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  email text NOT NULL,
  name text NOT NULL,
  role text NOT NULL CHECK (role IN (
    'ADMIN',
    'SALES_COORDINATOR',
    'BUYER',
    'PRODUCTION_PLANNER',
    'OPERATIONS_ANALYST',
    'ACCOUNTS_PAYABLE',
    'QUALITY_SPECIALIST'
  )),
  password_hash text NOT NULL,
  active boolean NOT NULL DEFAULT true,
  credential_version integer NOT NULL DEFAULT 1 CHECK (credential_version > 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE UNIQUE INDEX users_email_lower_unique ON users (lower(email));

CREATE TABLE records (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type text NOT NULL CHECK (type ~ '^[A-Z][A-Z0-9_]*$'),
  number text NOT NULL UNIQUE,
  title text NOT NULL,
  party text NOT NULL DEFAULT '',
  status text NOT NULL CHECK (status ~ '^[A-Z][A-Z0-9_]*$'),
  priority text NOT NULL DEFAULT 'NORMAL' CHECK (priority IN ('NORMAL', 'HIGH', 'URGENT')),
  owner text NOT NULL DEFAULT '',
  due_date date,
  data jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(data) = 'object'),
  version integer NOT NULL DEFAULT 1 CHECK (version > 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX records_type_status ON records (type, status);
CREATE INDEX records_priority_due_date ON records (priority, due_date);
CREATE INDEX records_owner_status ON records (owner, status);
CREATE INDEX records_data_gin ON records USING gin (data jsonb_path_ops);

CREATE TABLE record_relations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  parent_number text NOT NULL REFERENCES records(number) ON UPDATE CASCADE ON DELETE CASCADE,
  child_number text NOT NULL REFERENCES records(number) ON UPDATE CASCADE ON DELETE CASCADE,
  relation_type text NOT NULL CHECK (relation_type ~ '^[A-Z][A-Z0-9_]*$'),
  created_at timestamptz NOT NULL DEFAULT now(),
  CHECK (parent_number <> child_number),
  UNIQUE (parent_number, child_number, relation_type)
);

CREATE INDEX record_relations_child ON record_relations (child_number, relation_type);

CREATE TABLE record_cost_lines (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  record_number text NOT NULL REFERENCES records(number) ON UPDATE CASCADE ON DELETE CASCADE,
  category text NOT NULL CHECK (category IN (
    'MATERIAL',
    'OUTSIDE_PROCESSING',
    'LABOR',
    'MACHINE',
    'SETUP',
    'TOOLING',
    'PACKAGING',
    'FREIGHT',
    'SCRAP',
    'OVERHEAD',
    'OTHER'
  )),
  description text NOT NULL,
  quantity numeric(18, 4) NOT NULL DEFAULT 1 CHECK (quantity >= 0),
  unit_cost numeric(18, 4) NOT NULL DEFAULT 0 CHECK (unit_cost >= 0),
  extended_cost numeric(18, 2) GENERATED ALWAYS AS (round(quantity * unit_cost, 2)) STORED,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX record_cost_lines_record ON record_cost_lines (record_number, sort_order, id);

CREATE TABLE communications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  record_number text NOT NULL REFERENCES records(number) ON UPDATE CASCADE ON DELETE CASCADE,
  direction text NOT NULL DEFAULT 'OUTBOUND' CHECK (direction IN ('INBOUND', 'OUTBOUND', 'INTERNAL')),
  recipient text NOT NULL DEFAULT '',
  sender text NOT NULL DEFAULT '',
  subject text NOT NULL DEFAULT '',
  body text NOT NULL DEFAULT '',
  template text,
  sent_at timestamptz NOT NULL DEFAULT now(),
  status text NOT NULL DEFAULT 'SENT' CHECK (status IN ('DRAFT', 'QUEUED', 'SENT', 'FAILED', 'RECEIVED')),
  created_by text NOT NULL DEFAULT ''
);

CREATE INDEX communications_record_sent ON communications (record_number, sent_at DESC);

CREATE TABLE tasks (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  number text NOT NULL UNIQUE,
  title text NOT NULL,
  record_number text NOT NULL REFERENCES records(number) ON UPDATE CASCADE ON DELETE CASCADE,
  assigned_user text NOT NULL DEFAULT '',
  created_by text NOT NULL DEFAULT '',
  priority text NOT NULL DEFAULT 'NORMAL' CHECK (priority IN ('NORMAL', 'HIGH', 'URGENT')),
  due_date date,
  status text NOT NULL DEFAULT 'OPEN' CHECK (status IN ('OPEN', 'IN_PROGRESS', 'BLOCKED', 'COMPLETED', 'CANCELLED')),
  note text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX tasks_record_status ON tasks (record_number, status);
CREATE INDEX tasks_assignee_status_due ON tasks (assigned_user, status, due_date);

CREATE TABLE reports (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  number text NOT NULL UNIQUE,
  report_date date NOT NULL,
  prepared_by text NOT NULL,
  status text NOT NULL DEFAULT 'DRAFT' CHECK (status IN ('DRAFT', 'FINAL')),
  executive_summary text NOT NULL DEFAULT '',
  management_decisions text NOT NULL DEFAULT '',
  metrics jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metrics) = 'object'),
  finalized_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CHECK ((status = 'FINAL' AND finalized_at IS NOT NULL) OR status = 'DRAFT')
);

CREATE INDEX reports_date_status ON reports (report_date DESC, status);

CREATE TABLE report_records (
  report_id bigint NOT NULL REFERENCES reports(id) ON DELETE CASCADE,
  record_number text NOT NULL REFERENCES records(number) ON UPDATE CASCADE ON DELETE RESTRICT,
  included_by text NOT NULL,
  included_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (report_id, record_number)
);

CREATE INDEX report_records_record ON report_records (record_number);

CREATE TABLE northstar_sessions (
  token_hash char(64) PRIMARY KEY CHECK (token_hash ~ '^[0-9a-f]{64}$'),
  user_id bigint NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  credential_version integer NOT NULL CHECK (credential_version > 0),
  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  revoked_at timestamptz,
  user_agent text,
  CHECK (expires_at > created_at)
);

CREATE INDEX northstar_sessions_user ON northstar_sessions (user_id, expires_at DESC);
CREATE INDEX northstar_sessions_expiry ON northstar_sessions (expires_at) WHERE revoked_at IS NULL;

CREATE TABLE audit_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp timestamptz NOT NULL DEFAULT now(),
  user_name text NOT NULL,
  user_role text NOT NULL,
  module text NOT NULL,
  record_type text NOT NULL,
  record_number text NOT NULL,
  action text NOT NULL,
  field_changed text,
  previous_value text,
  new_value text,
  note text,
  session_id text NOT NULL,
  request_id uuid,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX audit_events_record_time ON audit_events (record_number, timestamp DESC);
CREATE INDEX audit_events_user_time ON audit_events (user_name, timestamp DESC);
CREATE INDEX audit_events_action_time ON audit_events (action, timestamp DESC);

CREATE FUNCTION northstar_set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER users_set_updated_at
BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION northstar_set_updated_at();

CREATE TRIGGER records_set_updated_at
BEFORE UPDATE ON records
FOR EACH ROW EXECUTE FUNCTION northstar_set_updated_at();

CREATE TRIGGER record_cost_lines_set_updated_at
BEFORE UPDATE ON record_cost_lines
FOR EACH ROW EXECUTE FUNCTION northstar_set_updated_at();

CREATE TRIGGER tasks_set_updated_at
BEFORE UPDATE ON tasks
FOR EACH ROW EXECUTE FUNCTION northstar_set_updated_at();

CREATE TRIGGER reports_set_updated_at
BEFORE UPDATE ON reports
FOR EACH ROW EXECUTE FUNCTION northstar_set_updated_at();

CREATE FUNCTION northstar_reject_audit_mutation()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  RAISE EXCEPTION 'audit_events is append-only';
END;
$$;

CREATE TRIGGER audit_events_append_only
BEFORE UPDATE OR DELETE ON audit_events
FOR EACH ROW EXECUTE FUNCTION northstar_reject_audit_mutation();

COMMENT ON TABLE audit_events IS 'Append-only evidence of meaningful Northstar actions.';
COMMENT ON TABLE northstar_sessions IS 'Opaque browser sessions; only SHA-256 token hashes are stored.';
COMMENT ON COLUMN records.version IS 'Optimistic concurrency version; increment on every domain mutation.';
