-- Content used by the record workspace and daily operations report editor.

CREATE TABLE notes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  record_number text NOT NULL REFERENCES records(number) ON UPDATE CASCADE ON DELETE CASCADE,
  body text NOT NULL CHECK (length(body) > 0),
  created_by text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX notes_record_created ON notes (record_number, created_at DESC);

ALTER TABLE reports
  ADD COLUMN narratives jsonb NOT NULL DEFAULT '{}'::jsonb
    CHECK (jsonb_typeof(narratives) = 'object'),
  ADD COLUMN internal_notes text NOT NULL DEFAULT '';
