import Database from "better-sqlite3";import path from "node:path";import {existsSync,execFileSync} from "node:fs";import {scryptSync,timingSafeEqual} from "node:crypto";
const file=process.env.NORTHSTAR_DATABASE_PATH||path.join(process.cwd(),"data/northstar.sqlite3");
if(!existsSync(file))execFileSync("node",[path.join(process.cwd(),"scripts/northstar-setup.mjs")]);
export const nsdb=new Database(file);nsdb.pragma("foreign_keys=ON");
export type NSRecord={id:number,type:string,number:string,title:string,party:string,status:string,priority:string,owner:string,due_date:string|null,data:string,updated_at:string};
export const records=(where="1=1",params:unknown[]=[])=>(nsdb.prepare(`SELECT * FROM records WHERE ${where} ORDER BY CASE priority WHEN 'URGENT' THEN 0 WHEN 'HIGH' THEN 1 ELSE 2 END,due_date LIMIT 100`).all(...params) as NSRecord[]).map(r=>({...r,data:JSON.parse(r.data||"{}")}));
export const record=(number:string)=>{const r=nsdb.prepare("SELECT * FROM records WHERE number=?").get(number) as NSRecord|undefined;return r?{...r,data:JSON.parse(r.data||"{}")} as NSRecord&{data:Record<string,any>}:null};
export function verify(password:string,stored:string){const [salt,key]=stored.split(":");return timingSafeEqual(Buffer.from(key,"hex"),scryptSync(password,salt,64))}
export function metrics(){const q=(sql:string,...p:unknown[])=>(nsdb.prepare(sql).pluck().get(...p) as number)||0;return {newRfqs:q("SELECT count(*) FROM records WHERE type='RFQ' AND status='NEW'"),quotes:q("SELECT count(*) FROM records WHERE type='QUOTE' AND status='AWAITING_APPROVAL'"),holds:q("SELECT count(*) FROM records WHERE type='SALES_ORDER' AND status='ON_HOLD'"),shortages:q("SELECT count(*) FROM records WHERE type='SHORTAGE' AND status!='RESOLVED'"),pastDuePOs:q("SELECT count(*) FROM records WHERE type='PURCHASE_ORDER' AND status='PAST_DUE'"),atRiskWOs:q("SELECT count(*) FROM records WHERE type='WORK_ORDER' AND status='MATERIAL_PENDING'"),quality:q("SELECT count(*) FROM records WHERE type='QUALITY_HOLD' AND status='QUALITY_HOLD'"),shipments:3,confirmations:q("SELECT count(*) FROM records WHERE type='PURCHASE_ORDER' AND json_extract(data,'$.confirmation')='AWAITING_RESPONSE'"),invoices:q("SELECT count(*) FROM records WHERE type='INVOICE' AND status IN ('PRICE_EXCEPTION','QUANTITY_EXCEPTION','MISSING_RECEIPT','MISSING_PO','ON_HOLD')")}}
export function audit(recordNumber:string,user:any,action:string,field?:string,oldValue?:unknown,newValue?:unknown,note?:string){const rec=record(recordNumber);nsdb.prepare("INSERT INTO audit_events(user,user_role,module,record_type,record_number,action,field_changed,previous_value,new_value,note,session_id) VALUES(?,?,?,?,?,?,?,?,?,?,?)").run(user.name,user.role,rec?.type||"System",rec?.type||"Record",recordNumber,action,field||null,oldValue==null?null:String(oldValue),newValue==null?null:String(newValue),note||null,user.session||"demo-session")}
