import {NextResponse} from "next/server";import {cookies} from "next/headers";import {nsdb,record,audit,metrics} from "@/lib/northstar";
function user(raw?:string){try{return JSON.parse(Buffer.from(raw||"","base64url").toString())}catch{return null}}
export async function POST(req:Request){const u=user((await cookies()).get("ns_user")?.value);if(!u)return NextResponse.json({error:"Sign in required"},{status:401});const b=await req.json();const r=record(b.number);if(!r)return NextResponse.json({error:"Record not found"},{status:404});const allowed:any={approve:["ADMIN"],invoiceHold:["ADMIN","ACCOUNTS_PAYABLE"],supplierFollowup:["ADMIN","BUYER"],transfer:["ADMIN","PRODUCTION_PLANNER"],requestInfo:["ADMIN","SALES_COORDINATOR"]};if(allowed[b.action]&&!allowed[b.action].includes(u.role))return NextResponse.json({error:"Your role is not authorized for this action."},{status:403});
 const data={...r.data};let field="status",old:any=r.status,value:any=r.status,note=b.note||"";const tx=nsdb.transaction(()=>{
  if(b.action==="requestInfo"){nsdb.prepare("INSERT INTO communications(record_number,recipient,sender,subject,body,template,created_by) VALUES(?,?,?,?,?,?,?)").run(r.number,b.recipient||"laura.bennett@apexmotion.example",u.email,"Information required for "+r.number,b.message||"Please provide the missing drawing revision and packaging requirements.","Customer information request",u.name);note="Customer information request sent"}
  else if(b.action==="updateRfq"){data.drawingRevision=b.drawingRevision;data.packaging=b.packaging;data.missing=[];value="COSTING";nsdb.prepare("UPDATE records SET status=?,data=?,updated_at=CURRENT_TIMESTAMP WHERE number=?").run(value,JSON.stringify(data),r.number)}
  else if(b.action==="approve"){value="APPROVED";nsdb.prepare("UPDATE records SET status=?,updated_at=CURRENT_TIMESTAMP WHERE number=?").run(value,r.number)}
  else if(b.action==="submitQuote"){if(r.status!=="APPROVED")throw new Error("This quote cannot be submitted because Sales Manager approval is still required.");value="SUBMITTED";nsdb.prepare("UPDATE records SET status=?,updated_at=CURRENT_TIMESTAMP WHERE number=?").run(value,r.number);nsdb.prepare("INSERT INTO communications(record_number,recipient,sender,subject,body,template,created_by) VALUES(?,?,?,?,?,?,?)").run(r.number,"laura.bennett@apexmotion.example",u.email,"Northstar quotation "+r.number,"Please find Northstar's quotation for your review.","Quote submission",u.name)}
  else if(b.action==="supplierFollowup"){data.lastFollowup=new Date().toISOString().slice(0,10);data.nextFollowup=b.nextFollowup;nsdb.prepare("UPDATE records SET data=?,updated_at=CURRENT_TIMESTAMP WHERE number=?").run(JSON.stringify(data),r.number);nsdb.prepare("INSERT INTO communications(record_number,recipient,sender,subject,body,template,created_by) VALUES(?,?,?,?,?,?,?)").run(r.number,b.recipient||data.contact,u.email,"Confirmation requested: "+r.number,b.message||"Please confirm pricing and delivery date.","Supplier confirmation follow-up",u.name);field="communication";old="";value="SENT"}
  else if(b.action==="confirmPO"){data.promisedDate=b.promisedDate;data.confirmation="REVISED_DATE";value="CONFIRMED";nsdb.prepare("UPDATE records SET status=?,data=?,updated_at=CURRENT_TIMESTAMP WHERE number=?").run(value,JSON.stringify(data),r.number)}
  else if(b.action==="task"){const n=`TASK-${Date.now().toString().slice(-6)}`;nsdb.prepare("INSERT INTO tasks(number,title,record_number,assigned_user,created_by,priority,due_date,note) VALUES(?,?,?,?,?,?,?,?)").run(n,b.title||"Supplier expedite",r.number,b.assignee||r.owner,u.name,b.priority||"HIGH",b.dueDate||null,b.note||"");field="task";old="";value=n}
  else if(b.action==="transfer"){const n=`TR-${Date.now().toString().slice(-6)}`;data.transfers=[...(data.transfers||[]),{number:n,from:b.from,quantity:Number(b.quantity),status:"SUBMITTED"}];nsdb.prepare("UPDATE records SET data=?,updated_at=CURRENT_TIMESTAMP WHERE number=?").run(JSON.stringify(data),r.number);field="transfer";old="";value=`${n}: ${b.quantity} LB from ${b.from}`}
  else if(b.action==="escalate"){value="ESCALATED";nsdb.prepare("UPDATE records SET status=?,updated_at=CURRENT_TIMESTAMP WHERE number=?").run(value,r.number)}
  else if(b.action==="updateException"){data.customerImpact=b.customerImpact;data.productionImpact=b.productionImpact;data.estimatedCompletion=b.estimatedCompletion;value=b.status||r.status;nsdb.prepare("UPDATE records SET status=?,owner=?,priority=?,data=?,updated_at=CURRENT_TIMESTAMP WHERE number=?").run(value,b.owner||r.owner,b.priority||r.priority,JSON.stringify(data),r.number)}
  else if(b.action==="invoiceHold"){data.hold=true;value="ON_HOLD";nsdb.prepare("UPDATE records SET status=?,data=?,updated_at=CURRENT_TIMESTAMP WHERE number=?").run(value,JSON.stringify(data),r.number)}
  else if(b.action==="creditRequest"){nsdb.prepare("INSERT INTO communications(record_number,recipient,sender,subject,body,template,created_by) VALUES(?,?,?,?,?,?,?)").run(r.number,"credits@summitsteel.example",u.email,"Credit request for "+r.number,b.message||"Please issue a credit for the unit price variance.","Supplier credit request",u.name);field="communication";old="";value="CREDIT_REQUEST_SENT"}
  else if(b.action==="note"){field="note";old="";value=note}
  audit(r.number,u,b.action,field,old,value,note);
 });try{tx()}catch(e:any){return NextResponse.json({error:e.message},{status:400})}return NextResponse.json({ok:true,record:record(b.number),metrics:metrics()})}
